<?php
//This file was automaticaly generated by L2JZ engine.
$config = array (
  'l2jzVersionId' => 'bc8fdb5dc8e4ba0',
  'javaScripts'=>array(
    0 => 'castles/castleEngine',
    1 => 'drop/recipeEngine',
    2 => 'main/imageLoader',
    3 => 'main/JS/menuLib',
    4 => 'main/JS/panelEngine',
    5 => 'main/JS/tableEngine',
    6 => 'main/JS/tooltipEngine',
    7 => 'map/mapEngine',
  ),
  'stylesheets'=>array(
    0 => 'main/style',
    1 => 'map/style',
  ),
  'languages'=>array(
    0 => 'english',
    1 => 'russian',
  ),
);
?>