<?php
//This file was automaticaly generated by L2JZ engine.
$l2jz = array (
  'account.main'=>array(
    'access' => 10,
    'sAccess' => 'myAccount',
    'vars'=>array(
      'login'=>array(
        'clearVar' => 'TRUE',
        'name' => 'login',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/account/phpHandlers/account/main.php',
      'l2j_ft' => 'modules/account/phpHandlers/account/main.l2j_ft.php',
    ),
  ),
  'account.chars'=>array(
    'access' => 10,
    'sAccess' => 'myAccount',
    'vars'=>array(
      'login'=>array(
        'clearVar' => 'TRUE',
        'name' => 'login',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/account/phpHandlers/account/chars.php',
      'l2j_ft' => 'modules/account/phpHandlers/account/chars.l2j_ft.php',
    ),
  ),
  'account.action.moveCharToAccount'=>array(
    'access' => 100,
    'vars'=>array(
      'login'=>array(
        'clearVar' => 'TRUE',
        'name' => 'login',
        'type' => 'login',
      ),
      'char_name'=>array(
        'clearVar' => 'TRUE',
        'name' => 'char_name',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/account/phpHandlers/account/action/moveCharToAccount.php',
      'l2j_ft' => 'modules/account/phpHandlers/account/action/moveCharToAccount.php',
    ),
  ),
  'account.action.changePass'=>array(
    'access' => 100,
    'vars'=>array(
      'login'=>array(
        'clearVar' => 'TRUE',
        'name' => 'login',
        'type' => 'login',
      ),
      'newPass'=>array(
        'clearVar' => 'TRUE',
        'name' => 'newPass',
        'type' => 'newPass',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/account/phpHandlers/account/action/changePass.php',
      'l2j_ft' => 'modules/account/phpHandlers/account/action/changePass.php',
    ),
  ),
  'account.action.changeMyPass'=>array(
    'access' => 0,
    'vars'=>array(
      'login'=>array(
        'clearVar' => 'TRUE',
        'name' => 'login',
        'type' => 'login',
      ),
      'pass'=>array(
        'clearVar' => 'TRUE',
        'name' => 'pass',
        'type' => 'pass',
      ),
      'newPass'=>array(
        'clearVar' => 'TRUE',
        'name' => 'newPass',
        'type' => 'newPass',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/account/phpHandlers/account/action/changeMyPass.php',
      'l2j_ft' => 'modules/account/phpHandlers/account/action/changeMyPass.php',
    ),
  ),
  'account.action.changeAccess'=>array(
    'access' => 100,
    'vars'=>array(
      'login'=>array(
        'clearVar' => 'TRUE',
        'name' => 'login',
        'type' => 'login',
      ),
      'builder'=>array(
        'clearVar' => 'TRUE',
        'name' => 'builder',
        'type' => 'numeric',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/account/phpHandlers/account/action/changeAccess.php',
      'l2j_ft' => 'modules/account/phpHandlers/account/action/changeAccess.php',
    ),
  ),
  'account.action.changeEmail'=>array(
    'access' => 100,
    'sAccess' => 'myAccount',
    'vars'=>array(
      'login'=>array(
        'clearVar' => 'TRUE',
        'name' => 'login',
        'type' => 'login',
      ),
      'email'=>array(
        'clearVar' => 'TRUE',
        'name' => 'email',
        'type' => 'email',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/account/phpHandlers/account/action/changeEmail.php',
      'l2j_ft' => 'modules/account/phpHandlers/account/action/changeEmail.php',
    ),
  ),
  'account.action.ban'=>array(
    'access' => 100,
    'vars'=>array(
      'login'=>array(
        'clearVar' => 'TRUE',
        'name' => 'login',
        'type' => 'login',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/account/phpHandlers/account/action/ban.php',
      'l2j_ft' => 'modules/account/phpHandlers/account/action/ban.php',
    ),
  ),
  'account.action.unban'=>array(
    'access' => 100,
    'vars'=>array(
      'login'=>array(
        'clearVar' => 'TRUE',
        'name' => 'login',
        'type' => 'login',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/account/phpHandlers/account/action/unban.php',
      'l2j_ft' => 'modules/account/phpHandlers/account/action/unban.php',
    ),
  ),
  'castles.main'=>array(
    'access' => 0,
    'cache' => 360,
    'handler'=>array(
      'default' => 'modules/castles/phpHandlers/castles/main.php',
      'l2j_ft' => 'modules/castles/phpHandlers/castles/main.php',
    ),
  ),
  'char.main'=>array(
    'access' => 10,
    'sAccess' => 'myChar',
    'vars'=>array(
      'char_id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'char_id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/char/phpHandlers/char/main.php',
      'l2j_ft' => 'modules/char/phpHandlers/char/main.l2j_ft.php',
    ),
  ),
  'char.inventory'=>array(
    'access' => 30,
    'sAccess' => 'myChar',
    'vars'=>array(
      'char_id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'char_id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/char/phpHandlers/char/inventory.php',
      'l2j_ft' => 'modules/char/phpHandlers/char/inventory.php',
    ),
  ),
  'char.skills'=>array(
    'access' => 10,
    'sAccess' => 'myChar',
    'vars'=>array(
      'char_id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'char_id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/char/phpHandlers/char/skills.php',
      'l2j_ft' => 'modules/char/phpHandlers/char/skills.php',
    ),
  ),
  'char.recipebook'=>array(
    'access' => 10,
    'sAccess' => 'myChar',
    'vars'=>array(
      'char_id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'char_id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/char/phpHandlers/char/recipebook.php',
      'l2j_ft' => 'modules/char/phpHandlers/char/recipebook.php',
    ),
  ),
  'char.friends'=>array(
    'access' => 10,
    'sAccess' => 'myChar',
    'vars'=>array(
      'char_id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'char_id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/char/phpHandlers/char/friends.php',
      'l2j_ft' => 'modules/char/phpHandlers/char/friends.l2j_ft.php',
    ),
  ),
  'char.action.main.kick'=>array(
    'access' => 100,
    'sAccess' => 'myChar',
    'vars'=>array(
      'char_id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'char_id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/char/phpHandlers/char/action/main/kick.php',
      'l2j_ft' => 'modules/char/phpHandlers/char/action/main/kick.php',
    ),
  ),
  'char.action.main.changeAccess'=>array(
    'access' => 100,
    'sAccess' => 'myChar',
    'vars'=>array(
      'char_id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'char_id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/char/phpHandlers/char/action/main/changeAccess.php',
      'l2j_ft' => 'modules/char/phpHandlers/char/action/main/changeAccess.php',
    ),
  ),
  'char.action.main.sendWhisper'=>array(
    'access' => 10,
    'sAccess' => 'myChar',
    'vars'=>array(
      'char_id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'char_id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/char/phpHandlers/char/action/main/sendWhisper.php',
      'l2j_ft' => 'modules/char/phpHandlers/char/action/main/sendWhisper.php',
    ),
  ),
  'char.action.main.changeClass'=>array(
    'access' => 100,
    'sAccess' => 'myChar',
    'vars'=>array(
      'char_id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'char_id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/char/phpHandlers/char/action/main/changeClass.php',
      'l2j_ft' => 'modules/char/phpHandlers/char/action/main/changeClass.php',
    ),
  ),
  'char.action.main.changeName'=>array(
    'access' => 100,
    'sAccess' => 'myChar',
    'vars'=>array(
      'char_id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'char_id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/char/phpHandlers/char/action/main/changeName.php',
      'l2j_ft' => 'modules/char/phpHandlers/char/action/main/changeName.php',
    ),
  ),
  'char.action.main.teleport'=>array(
    'access' => 100,
    'sAccess' => 'myChar',
    'vars'=>array(
      'char_id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'char_id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/char/phpHandlers/char/action/main/teleport.php',
      'l2j_ft' => 'modules/char/phpHandlers/char/action/main/teleport.php',
    ),
  ),
  'char.action.main.moveToAccount'=>array(
    'access' => 100,
    'sAccess' => 'myChar',
    'vars'=>array(
      'char_id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'char_id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/char/phpHandlers/char/action/main/moveToAccount.php',
      'l2j_ft' => 'modules/char/phpHandlers/char/action/main/moveToAccount.php',
    ),
  ),
  'char.action.skills.addSkill'=>array(
    'access' => 100,
    'sAccess' => 'myChar',
    'vars'=>array(
      'char_id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'char_id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/char/phpHandlers/char/action/skills/addSkill.php',
      'l2j_ft' => 'modules/char/phpHandlers/char/action/skills/addSkill.php',
    ),
  ),
  'char.action.skills.setSkillLevel'=>array(
    'access' => 100,
    'sAccess' => 'myChar',
    'vars'=>array(
      'char_id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'char_id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/char/phpHandlers/char/action/skills/setSkillLevel.php',
      'l2j_ft' => 'modules/char/phpHandlers/char/action/skills/setSkillLevel.php',
    ),
  ),
  'char.action.skills.deleteSkill'=>array(
    'access' => 100,
    'sAccess' => 'myChar',
    'vars'=>array(
      'char_id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'char_id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/char/phpHandlers/char/action/skills/deleteSkill.php',
      'l2j_ft' => 'modules/char/phpHandlers/char/action/skills/deleteSkill.php',
    ),
  ),
  'char.action.item.addItem'=>array(
    'access' => 100,
    'sAccess' => 'myChar',
    'vars'=>array(
      'char_id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'char_id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/char/phpHandlers/char/action/item/addItem.php',
      'l2j_ft' => 'modules/char/phpHandlers/char/action/item/addItem.php',
    ),
  ),
  'char.action.item.changeItemCount'=>array(
    'access' => 100,
    'sAccess' => 'myChar',
    'vars'=>array(
      'char_id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'char_id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/char/phpHandlers/char/action/item/changeItemCount.php',
      'l2j_ft' => 'modules/char/phpHandlers/char/action/item/changeItemCount.php',
    ),
  ),
  'char.action.item.deleteItem'=>array(
    'access' => 100,
    'sAccess' => 'myChar',
    'vars'=>array(
      'char_id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'char_id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/char/phpHandlers/char/action/item/deleteItem.php',
      'l2j_ft' => 'modules/char/phpHandlers/char/action/item/deleteItem.php',
    ),
  ),
  'char.action.item.enchantItem'=>array(
    'access' => 100,
    'sAccess' => 'myChar',
    'vars'=>array(
      'char_id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'char_id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/char/phpHandlers/char/action/item/enchantItem.php',
      'l2j_ft' => 'modules/char/phpHandlers/char/action/item/enchantItem.php',
    ),
  ),
  'clan.main'=>array(
    'access' => 0,
    'sAccess' => 'myClan',
    'vars'=>array(
      'clan_id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'clan_id',
        'type' => 'none',
      ),
    ),
    'cache' => 3600,
    'handler'=>array(
      'default' => 'modules/clan/phpHandlers/clan/main.php',
      'l2j_ft' => 'modules/clan/phpHandlers/clan/main.l2j_ft.php',
    ),
  ),
  'clan.warehouse'=>array(
    'access' => 30,
    'sAccess' => 'myClan',
    'vars'=>array(
      'clan_id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'clan_id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/clan/phpHandlers/clan/warehouse.php',
      'l2j_ft' => 'modules/clan/phpHandlers/clan/warehouse.php',
    ),
  ),
  'clan.chars'=>array(
    'access' => 0,
    'sAccess' => 'myClan',
    'vars'=>array(
      'clan_id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'clan_id',
        'type' => 'none',
      ),
    ),
    'cache' => 3600,
    'handler'=>array(
      'default' => 'modules/clan/phpHandlers/clan/chars.php',
      'l2j_ft' => 'modules/clan/phpHandlers/clan/chars.l2j_ft.php',
    ),
  ),
  'item.main'=>array(
    'access' => 0,
    'vars'=>array(
      'id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'id',
        'type' => 'none',
      ),
    ),
    'cache' => 3600,
    'handler'=>array(
      'default' => 'modules/drop/phpHandlers/item/main.php',
      'l2j_ft' => 'modules/drop/phpHandlers/item/main.php',
    ),
  ),
  'item.drop'=>array(
    'access' => 0,
    'vars'=>array(
      'id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/drop/phpHandlers/item/drop.php',
      'l2j_ft' => 'modules/drop/phpHandlers/item/drop.php',
    ),
  ),
  'item.sell'=>array(
    'access' => 0,
    'vars'=>array(
      'id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/drop/phpHandlers/item/sell.php',
      'l2j_ft' => 'modules/drop/phpHandlers/item/sell.php',
    ),
  ),
  'item.recipe'=>array(
    'access' => 0,
    'vars'=>array(
      'id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/drop/phpHandlers/item/recipe.php',
      'l2j_ft' => 'modules/drop/phpHandlers/item/recipe.php',
    ),
  ),
  'item.owners'=>array(
    'access' => 30,
    'vars'=>array(
      'id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/drop/phpHandlers/item/owners.php',
      'l2j_ft' => 'modules/drop/phpHandlers/item/owners.l2j_ft.php',
    ),
  ),
  'monster.main'=>array(
    'access' => 0,
    'vars'=>array(
      'id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/drop/phpHandlers/monster/main.php',
      'l2j_ft' => 'modules/drop/phpHandlers/monster/main.php',
    ),
  ),
  'monster.drop'=>array(
    'access' => 0,
    'vars'=>array(
      'id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/drop/phpHandlers/monster/drop.php',
      'l2j_ft' => 'modules/drop/phpHandlers/monster/drop.php',
    ),
  ),
  'monster.sell'=>array(
    'access' => 0,
    'vars'=>array(
      'id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/drop/phpHandlers/monster/sell.php',
      'l2j_ft' => 'modules/drop/phpHandlers/monster/sell.php',
    ),
  ),
  'monster.skills'=>array(
    'access' => 0,
    'vars'=>array(
      'id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/drop/phpHandlers/monster/skills.php',
      'l2j_ft' => 'modules/drop/phpHandlers/monster/skills.php',
    ),
  ),
  'monster.minions'=>array(
    'access' => 0,
    'vars'=>array(
      'id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/drop/phpHandlers/monster/minions.php',
      'l2j_ft' => 'modules/drop/phpHandlers/monster/minions.php',
    ),
  ),
  'info.welcome'=>array(
    'access' => 0,
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/info/welcome.php',
      'l2j_ft' => 'modules/main/phpHandlers/info/welcome.php',
    ),
  ),
  'chars.builders'=>array(
    'access' => 0,
    'cache' => 3600,
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/chars/builders.php',
      'l2j_ft' => 'modules/main/phpHandlers/chars/builders.l2j_ft.php',
    ),
  ),
  'chars.online'=>array(
    'access' => 0,
    'cache' => 180,
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/chars/online.php',
      'l2j_ft' => 'modules/main/phpHandlers/chars/online.l2j_ft.php',
    ),
  ),
  'chars.top100'=>array(
    'access' => 0,
    'cache' => 3600,
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/chars/top100.php',
      'l2j_ft' => 'modules/main/phpHandlers/chars/top100.l2j_ft.php',
    ),
  ),
  'chars.top100adena'=>array(
    'access' => 0,
    'cache' => 3600,
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/chars/top100adena.php',
      'l2j_ft' => 'modules/main/phpHandlers/chars/top100adena.l2j_ft.php',
    ),
  ),
  'chars.search'=>array(
    'access' => 10,
    'vars'=>array(
      'id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'id',
        'type' => 'string',
        'minlength' => 2,
      ),
    ),
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/chars/search.php',
      'l2j_ft' => 'modules/main/phpHandlers/chars/search.l2j_ft.php',
    ),
  ),
  'accounts.all'=>array(
    'access' => 10,
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/accounts/all.php',
      'l2j_ft' => 'modules/main/phpHandlers/accounts/all.l2j_ft.php',
    ),
  ),
  'accounts.builders'=>array(
    'access' => 10,
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/accounts/builders.php',
      'l2j_ft' => 'modules/main/phpHandlers/accounts/builders.l2j_ft.php',
    ),
  ),
  'accounts.search'=>array(
    'access' => 10,
    'vars'=>array(
      'id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'id',
        'type' => 'string',
        'minlength' => 2,
      ),
    ),
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/accounts/search.php',
      'l2j_ft' => 'modules/main/phpHandlers/accounts/search.l2j_ft.php',
    ),
  ),
  'clans.all_clans'=>array(
    'access' => 0,
    'cache' => 3600,
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/clans/all_clans.php',
      'l2j_ft' => 'modules/main/phpHandlers/clans/all_clans.l2j_ft.php',
    ),
  ),
  'clans.search'=>array(
    'access' => 0,
    'vars'=>array(
      'id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'id',
        'type' => 'string',
        'minlength' => 2,
      ),
    ),
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/clans/search.php',
      'l2j_ft' => 'modules/main/phpHandlers/clans/search.l2j_ft.php',
    ),
  ),
  'items.type'=>array(
    'access' => 0,
    'cache' => 3600,
    'vars'=>array(
      'id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/items/type.php',
      'l2j_ft' => 'modules/main/phpHandlers/items/type.php',
    ),
  ),
  'items.recipe'=>array(
    'access' => 0,
    'cache' => 3600,
    'vars'=>array(
      'id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/items/recipe.php',
      'l2j_ft' => 'modules/main/phpHandlers/items/recipe.php',
    ),
  ),
  'items.sets'=>array(
    'access' => 0,
    'cache' => 3600,
    'vars'=>array(
      'id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/items/sets.php',
      'l2j_ft' => 'modules/main/phpHandlers/items/sets.php',
    ),
  ),
  'items.luxor'=>array(
    'access' => 0,
    'cache' => 3600,
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/items/luxor.php',
      'l2j_ft' => 'modules/main/phpHandlers/items/luxor.php',
    ),
  ),
  'items.search'=>array(
    'access' => 0,
    'vars'=>array(
      'id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'id',
        'type' => 'string',
        'minlength' => 2,
      ),
    ),
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/items/search.php',
      'l2j_ft' => 'modules/main/phpHandlers/items/search.php',
    ),
  ),
  'monsters.type'=>array(
    'access' => 0,
    'cache' => 3600,
    'vars'=>array(
      'id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/monsters/type.php',
      'l2j_ft' => 'modules/main/phpHandlers/monsters/type.php',
    ),
  ),
  'monsters.search'=>array(
    'access' => 0,
    'vars'=>array(
      'id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'id',
        'type' => 'string',
        'minlength' => 2,
      ),
    ),
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/monsters/search.php',
      'l2j_ft' => 'modules/main/phpHandlers/monsters/search.php',
    ),
  ),
  'engine.user.register'=>array(
    'access' => 0,
    'vars'=>array(
      'login'=>array(
        'clearVar' => 'TRUE',
        'name' => 'login',
        'type' => 'newLogin',
      ),
      'pass'=>array(
        'clearVar' => 'TRUE',
        'name' => 'pass',
        'type' => 'newPass',
      ),
      'email'=>array(
        'clearVar' => 'TRUE',
        'name' => 'email',
        'type' => 'email',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/engine/user/register.php',
      'l2j_ft' => 'modules/main/phpHandlers/engine/user/register.php',
    ),
  ),
  'engine.user.login'=>array(
    'access' => 0,
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/engine/user/login.php',
      'l2j_ft' => 'modules/main/phpHandlers/engine/user/login.php',
    ),
  ),
  'engine.user.getPassByMail'=>array(
    'access' => 0,
    'vars'=>array(
      'login'=>array(
        'clearVar' => 'TRUE',
        'name' => 'login',
        'type' => 'login',
      ),
      'email'=>array(
        'clearVar' => 'TRUE',
        'name' => 'email',
        'type' => 'email',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/engine/user/getPassByMail.php',
      'l2j_ft' => 'modules/main/phpHandlers/engine/user/getPassByMail.php',
    ),
  ),
  'engine.user.exit'=>array(
    'access' => 0,
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/engine/user/exit.php',
      'l2j_ft' => 'modules/main/phpHandlers/engine/user/exit.php',
    ),
  ),
  'engine.mloader'=>array(
    'access' => 0,
    'vars'=>array(
      'moduleName'=>array(
        'clearVar' => 'TRUE',
        'name' => 'moduleName',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/engine/mloader.php',
      'l2j_ft' => 'modules/main/phpHandlers/engine/mloader.php',
    ),
  ),
  'engine.languageLoader'=>array(
    'access' => 0,
    'vars'=>array(
      'languageName'=>array(
        'clearVar' => 'TRUE',
        'name' => 'languageName',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/engine/languageLoader.php',
      'l2j_ft' => 'modules/main/phpHandlers/engine/languageLoader.php',
    ),
  ),
  'engine.changeGS'=>array(
    'access' => 0,
    'vars'=>array(
      'GS'=>array(
        'clearVar' => 'TRUE',
        'name' => 'GS',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/engine/changeGS.php',
      'l2j_ft' => 'modules/main/phpHandlers/engine/changeGS.php',
    ),
  ),
  'engine.compileL2JZ'=>array(
    'access' => 100,
    'handler'=>array(
      'default' => 'modules/main/phpHandlers/engine/compileL2JZ.php',
      'l2j_ft' => 'modules/main/phpHandlers/engine/compileL2JZ.php',
    ),
  ),
  'map.char'=>array(
    'access' => 10,
    'sAccess' => 'myChar',
    'vars'=>array(
      'char_id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'char_id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/map/phpHandlers/map/char.php',
      'l2j_ft' => 'modules/map/phpHandlers/map/char.l2j_ft.php',
    ),
  ),
  'map.monster'=>array(
    'access' => 0,
    'vars'=>array(
      'id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/map/phpHandlers/map/monster.php',
      'l2j_ft' => 'modules/map/phpHandlers/map/monster.php',
    ),
  ),
  'map.item'=>array(
    'access' => 0,
    'vars'=>array(
      'id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/map/phpHandlers/map/item.php',
      'l2j_ft' => 'modules/map/phpHandlers/map/item.php',
    ),
  ),
  'map.chars_online'=>array(
    'access' => 10,
    'cache' => 180,
    'handler'=>array(
      'default' => 'modules/map/phpHandlers/map/chars_online.php',
      'l2j_ft' => 'modules/map/phpHandlers/map/chars_online.l2j_ft.php',
    ),
  ),
  'map.clan'=>array(
    'access' => 10,
    'vars'=>array(
      'clan_id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'clan_id',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/map/phpHandlers/map/clan.php',
      'l2j_ft' => 'modules/map/phpHandlers/map/clan.l2j_ft.php',
    ),
  ),
  'quickAsk.char'=>array(
    'access' => 0,
    'vars'=>array(
      'id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'id',
        'type' => 'string',
        'minlength' => 2,
      ),
    ),
    'handler'=>array(
      'default' => 'modules/quickAsk/phpHandlers/quickAsk/char.php',
      'l2j_ft' => 'modules/quickAsk/phpHandlers/quickAsk/char.l2j_ft.php',
    ),
  ),
  'quickAsk.item'=>array(
    'access' => 0,
    'vars'=>array(
      'id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'id',
        'type' => 'string',
        'minlength' => 2,
      ),
    ),
    'handler'=>array(
      'default' => 'modules/quickAsk/phpHandlers/quickAsk/item.php',
      'l2j_ft' => 'modules/quickAsk/phpHandlers/quickAsk/item.php',
    ),
  ),
  'quickAsk.mob'=>array(
    'access' => 0,
    'vars'=>array(
      'id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'id',
        'type' => 'string',
        'minlength' => 2,
      ),
    ),
    'handler'=>array(
      'default' => 'modules/quickAsk/phpHandlers/quickAsk/mob.php',
      'l2j_ft' => 'modules/quickAsk/phpHandlers/quickAsk/mob.php',
    ),
  ),
  'server.main'=>array(
    'access' => 0,
    'cache' => 3600,
    'handler'=>array(
      'default' => 'modules/server/phpHandlers/server/main.php',
      'l2j_ft' => 'modules/server/phpHandlers/server/main.l2j_ft.php',
    ),
  ),
  'server.action.setAnnouncement'=>array(
    'access' => 100,
    'vars'=>array(
      'announce'=>array(
        'clearVar' => 'TRUE',
        'name' => 'announce',
        'type' => 'none',
      ),
    ),
    'handler'=>array(
      'default' => 'modules/server/phpHandlers/server/action/setAnnouncement.php',
      'l2j_ft' => 'modules/server/phpHandlers/server/action/setAnnouncement.php',
    ),
  ),
  'sevensigns.main'=>array(
    'access' => 0,
    'cache' => 3600,
    'handler'=>array(
      'default' => 'modules/sevensigns/phpHandlers/sevensigns/main.php',
      'l2j_ft' => 'modules/sevensigns/phpHandlers/sevensigns/main.l2j_ft.php',
    ),
  ),
  'skills.class'=>array(
    'access' => 0,
    'vars'=>array(
      'id'=>array(
        'clearVar' => 'TRUE',
        'name' => 'id',
        'type' => 'none',
      ),
    ),
    'cache' => 3600,
    'handler'=>array(
      'default' => 'modules/skills/phpHandlers/skills/class.php',
      'l2j_ft' => 'modules/skills/phpHandlers/skills/class.php',
    ),
  ),
);
?>